// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qpoint-io/qtap/pkg/services/objectstore (interfaces: ObjectStore)
//
// Generated by this command:
//
//	mockgen -destination ./objectstore_mock.go -package objectstore . ObjectStore
//

// Package objectstore is a generated GoMock package.
package objectstore

import (
	context "context"
	reflect "reflect"

	services "github.com/qpoint-io/qtap/pkg/services"
	eventstore "github.com/qpoint-io/qtap/pkg/services/eventstore"
	gomock "go.uber.org/mock/gomock"
)

// MockObjectStore is a mock of ObjectStore interface.
type MockObjectStore struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStoreMockRecorder
	isgomock struct{}
}

// MockObjectStoreMockRecorder is the mock recorder for MockObjectStore.
type MockObjectStoreMockRecorder struct {
	mock *MockObjectStore
}

// NewMockObjectStore creates a new mock instance.
func NewMockObjectStore(ctrl *gomock.Controller) *MockObjectStore {
	mock := &MockObjectStore{ctrl: ctrl}
	mock.recorder = &MockObjectStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStore) EXPECT() *MockObjectStoreMockRecorder {
	return m.recorder
}

// Put mocks base method.
func (m *MockObjectStore) Put(ctx context.Context, artifact *eventstore.Artifact) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Put", ctx, artifact)
}

// Put indicates an expected call of Put.
func (mr *MockObjectStoreMockRecorder) Put(ctx, artifact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockObjectStore)(nil).Put), ctx, artifact)
}

// ServiceType mocks base method.
func (m *MockObjectStore) ServiceType() services.ServiceType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceType")
	ret0, _ := ret[0].(services.ServiceType)
	return ret0
}

// ServiceType indicates an expected call of ServiceType.
func (mr *MockObjectStoreMockRecorder) ServiceType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceType", reflect.TypeOf((*MockObjectStore)(nil).ServiceType))
}

// ServiceEndpoints mocks base method.
func (m *MockObjectStore) ServiceEndpoints() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceEndpoints")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ServiceEndpoints indicates an expected call of ServiceEndpoints.
func (mr *MockObjectStoreMockRecorder) ServiceEndpoints() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceEndpoints", reflect.TypeOf((*MockObjectStore)(nil).ServiceEndpoints))
}
