// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package tap

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type CertsCertKey struct {
	Pid      uint32
	FilePath [256]int8
}

// LoadCerts returns the embedded CollectionSpec for Certs.
func LoadCerts() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CertsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Certs: %w", err)
	}

	return spec, err
}

// LoadCertsObjects loads Certs and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CertsObjects
//	*CertsPrograms
//	*CertsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCertsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadCerts()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CertsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CertsSpecs struct {
	CertsProgramSpecs
	CertsMapSpecs
	CertsVariableSpecs
}

// CertsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CertsProgramSpecs struct {
	MonitorCertOpenEntry *ebpf.ProgramSpec `ebpf:"monitor_cert_open_entry"`
	MonitorCertStatEntry *ebpf.ProgramSpec `ebpf:"monitor_cert_stat_entry"`
}

// CertsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CertsMapSpecs struct {
	CertEvents *ebpf.MapSpec `ebpf:"cert_events"`
	PidCertMap *ebpf.MapSpec `ebpf:"pid_cert_map"`
}

// CertsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CertsVariableSpecs struct {
}

// CertsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCertsObjects or ebpf.CollectionSpec.LoadAndAssign.
type CertsObjects struct {
	CertsPrograms
	CertsMaps
	CertsVariables
}

func (o *CertsObjects) Close() error {
	return _CertsClose(
		&o.CertsPrograms,
		&o.CertsMaps,
	)
}

// CertsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCertsObjects or ebpf.CollectionSpec.LoadAndAssign.
type CertsMaps struct {
	CertEvents *ebpf.Map `ebpf:"cert_events"`
	PidCertMap *ebpf.Map `ebpf:"pid_cert_map"`
}

func (m *CertsMaps) Close() error {
	return _CertsClose(
		m.CertEvents,
		m.PidCertMap,
	)
}

// CertsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadCertsObjects or ebpf.CollectionSpec.LoadAndAssign.
type CertsVariables struct {
}

// CertsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCertsObjects or ebpf.CollectionSpec.LoadAndAssign.
type CertsPrograms struct {
	MonitorCertOpenEntry *ebpf.Program `ebpf:"monitor_cert_open_entry"`
	MonitorCertStatEntry *ebpf.Program `ebpf:"monitor_cert_stat_entry"`
}

func (p *CertsPrograms) Close() error {
	return _CertsClose(
		p.MonitorCertOpenEntry,
		p.MonitorCertStatEntry,
	)
}

func _CertsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed certs_arm64_bpfel.o
var _CertsBytes []byte
