package conversations

import (
	"crypto/sha1"
	"encoding/hex"
	"fmt"
	"strconv"
	"sync"
	"time"

	lru "github.com/hashicorp/golang-lru/v2"
	"github.com/rs/xid"
)

const DefaultCacheSize = 1024

type Completion struct {
	// ID is the unique identifier for the completion.
	// A random ID will be set by the tracker.
	ID string

	// ParentID is the ID of the parent completion.
	// The tracker will attempt to locate the parent completion and set this field accordingly.
	ParentID string

	// ProviderID is the ID of the completion as provided by the provider.
	// This is used to track stateful completion APIs where the full conversation history is not provided.
	ProviderID string

	// ProviderParentID is the ID of the parent completion as provided by the provider.
	// This is used to track stateful completion APIs where the full conversation history is not provided.
	ProviderParentID string

	Timestamp time.Time
	Provider  string
	Model     string
	Messages  []*Message

	// Error is the error message returned by the provider.
	Error string
}

type Message struct {
	Role    string
	Content []MessageContent
}

type MessageContent struct {
	// Type describes the format of the data. If empty, the data is assumed to be a plaintext string.
	Type string
	Data string
}

// NewTextMessage is a helper function for creating a new message with the given role and text.
func NewTextMessage(role string, text ...string) *Message {
	content := make([]MessageContent, len(text))
	for i, t := range text {
		content[i] = MessageContent{Data: t}
	}
	return &Message{
		Role:    role,
		Content: content,
	}
}

type Tracker struct {
	mux sync.Mutex
	// completionIDByHash stores a map of completion hashes to their IDs generated by idGenerator.
	completionIDByHash *lru.Cache[string, string]
	// completionIDByProviderID stores a map of provider-specific completion IDs to their IDs generated by idGenerator.
	// This is used to track stateful completion APIs.
	completionIDByProviderID *lru.Cache[string, string]

	idGenerator idGenerator
}

func NewTracker() *Tracker {
	hashCache, _ := lru.New[string, string](DefaultCacheSize)
	providerIDCache, _ := lru.New[string, string](DefaultCacheSize)
	return &Tracker{
		completionIDByHash:       hashCache,
		completionIDByProviderID: providerIDCache,
		idGenerator:              &xidGenerator{},
	}
}

func (c *Completion) Hash() string {
	hash := sha1.New()
	hash.Write([]byte(c.Provider))
	hash.Write([]byte(c.providerParentID()))
	hash.Write([]byte(c.providerID()))
	hash.Write([]byte(c.Model))
	hash.Write([]byte(c.Error))
	hash.Write([]byte("\n"))
	for _, msg := range c.Messages {
		hash.Write([]byte(msg.Role))
		fmt.Fprintf(hash, "%d;", len(msg.Content))
		for i, content := range msg.Content {
			fmt.Fprintf(hash, "%d;%s;%s", i, content.Type, content.Data)
		}
		hash.Write([]byte("\n"))
	}
	return hex.EncodeToString(hash.Sum(nil))
}

// TrackCompletion tracks a completion request.
//
// For stateful completions, the provider must set the ProviderID and ProviderParentID fields.
// For stateless completions, this method will deduplicate the completion's messages
// based on known previous completions and return a new completion with a parent identifier and message
// diff.
//
// If the completion is already stored, `nil` will be returned.
func (c *Tracker) TrackCompletion(comp Completion) *Completion {
	c.mux.Lock()
	defer c.mux.Unlock()

	// check if we have already tracked this completion.
	hash := comp.Hash()
	if _, ok := c.completionIDByHash.Get(hash); ok {
		return nil
	}

	// assign a new random ID.
	comp.ID = c.idGenerator.New()
	// store a reference to the provider-specific ID if available.
	if comp.providerID() != "" {
		c.completionIDByProviderID.Add(comp.providerID(), comp.ID)
	}

	// update the hash->ID map.
	c.completionIDByHash.Add(hash, comp.ID)

	// if the provider set a parent ID, use it to find the parent completion.
	if providerParentID := comp.providerParentID(); providerParentID != "" {
		if parent, ok := c.completionIDByProviderID.Get(providerParentID); ok {
			comp.ParentID = parent
			return &comp
		}
	}

	// otherwise, attempt to find the parent completion based on the messages.
	comp = c.deduplicate(comp)
	return &comp
}

func (c *Tracker) deduplicate(comp Completion) Completion {
	// search for the closest known parent.
	// once identified, record its ID and only retain the message diff.
	for offset := len(comp.Messages) - 1; offset >= 0; offset-- {
		possibleParent := &Completion{
			Provider: comp.Provider,
			Model:    comp.Model,
			Messages: comp.Messages[:offset],
		}
		hash := possibleParent.Hash()
		if parent, ok := c.completionIDByHash.Get(hash); ok {
			comp.ParentID = parent
			comp.Messages = comp.Messages[offset:]
			break
		}
	}

	return comp
}

type idGenerator interface {
	New() string
}

type xidGenerator struct{}

func (x *xidGenerator) New() string {
	return xid.New().String()
}

type seqGenerator struct {
	seq int
}

func (s *seqGenerator) New() string {
	s.seq++
	return strconv.Itoa(s.seq)
}

func (c *Completion) providerID() string {
	if c.ProviderID == "" {
		return ""
	}
	return fmt.Sprintf("%s:%s", c.Provider, c.ProviderID)
}

func (c *Completion) providerParentID() string {
	if c.ProviderParentID == "" {
		return ""
	}
	return fmt.Sprintf("%s:%s", c.Provider, c.ProviderParentID)
}
