version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - cyclop
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - govet
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - musttag
    - nakedret
    - nilerr
    - nosprintfhostport
    - perfsprint
    - sqlclosecheck
    - staticcheck
    - testifylint
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  settings:
    cyclop:
      max-complexity: 50
      package-average: 25
    errcheck:
      check-type-assertions: false
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - godot
        source: (noinspection|TODO)
      - linters:
          - gocritic
        source: //noinspection
      - linters:
          - bodyclose
          - dupl
          - funlen
          - goconst
          - gosec
          - noctx
          - wrapcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 25
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
