# Fluent Bit Configuration for Qtap HTTP Transaction Logging to Axiom
# =====================================================================
#
# This configuration file sets up Fluent Bit to:
#
# 1. Receive logs from Docker containers using the Fluentd forward protocol
# 2. Filter logs specifically from the Qtap container (tagged as docker.qtap)
# 3. Parse the logs as JSON using the generic_json_parser defined in parsers.conf
# 4. Identify HTTP transaction logs by matching the message "HTTP transaction"
# 5. Rewrite the tag for these HTTP transaction logs to "qtap.http"
# 6. Upload the HTTP transaction logs to axiom
#
# This setup allows for easy viewing and processing of Qtap's HTTP transaction
# monitoring data while filtering out other container logs.

# Ensure the parsers are loaded
[SERVICE]
    Parsers_File    parsers.conf

# Listen for logs forwarded via fluentd log driver
[INPUT]
    Name        forward
    Listen      0.0.0.0
    Port        24224

# Filter the logs to only tagged with docker.qtap, and parse them as JSON
[FILTER]
    Name        parser
    Match       docker.qtap
    Key_Name    log          
    Parser      generic_json_parser

# Rewrite tag for logs with the exact message "HTTP transaction"
[FILTER]
    Name            rewrite_tag
    Match           docker.qtap
    Rule            $msg "^HTTP transaction$" qtap.http false

# Rewrite tag for logs headed to axiom so we can filter them out later
[FILTER]
    Name            rewrite_tag
    Match           qtap.http
    Rule            $url "^https://api.axiom.co" axiom.http false

# Output the HTTP transaction logs to axiom
[OUTPUT]
    Name                http
    Match               qtap.http
    Host                api.axiom.co
    Port                443
    URI                 /v1/datasets/${AXIOM_DATASET}/ingest
    Header              Authorization Bearer ${AXIOM_API_KEY}
    compress            gzip
    format              json
    json_date_key       date
    json_date_format    double
    tls                 On

# Output all other docker.qtap logs to stdout
# [OUTPUT]
#     Name         stdout
#     Match        docker.qtap
#     Format       json_lines
