// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qpoint-io/qtap/pkg/services/eventstore (interfaces: EventStore)
//
// Generated by this command:
//
//	mockgen -destination ./eventstore_mock.go -package eventstore . EventStore
//

// Package eventstore is a generated GoMock package.
package eventstore

import (
	context "context"
	reflect "reflect"

	services "github.com/qpoint-io/qtap/pkg/services"
	gomock "go.uber.org/mock/gomock"
)

// MockEventStore is a mock of EventStore interface.
type MockEventStore struct {
	ctrl     *gomock.Controller
	recorder *MockEventStoreMockRecorder
	isgomock struct{}
}

// MockEventStoreMockRecorder is the mock recorder for MockEventStore.
type MockEventStoreMockRecorder struct {
	mock *MockEventStore
}

// NewMockEventStore creates a new mock instance.
func NewMockEventStore(ctrl *gomock.Controller) *MockEventStore {
	mock := &MockEventStore{ctrl: ctrl}
	mock.recorder = &MockEventStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventStore) EXPECT() *MockEventStoreMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockEventStore) Save(ctx context.Context, item any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Save", ctx, item)
}

// Save indicates an expected call of Save.
func (mr *MockEventStoreMockRecorder) Save(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockEventStore)(nil).Save), ctx, item)
}

// ServiceType mocks base method.
func (m *MockEventStore) ServiceType() services.ServiceType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceType")
	ret0, _ := ret[0].(services.ServiceType)
	return ret0
}

// ServiceType indicates an expected call of ServiceType.
func (mr *MockEventStoreMockRecorder) ServiceType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceType", reflect.TypeOf((*MockEventStore)(nil).ServiceType))
}

// ServiceEndpoints mocks base method.
func (m *MockEventStore) ServiceEndpoints() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceEndpoints")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ServiceEndpoints indicates an expected call of ServiceEndpoints.
func (mr *MockEventStoreMockRecorder) ServiceEndpoints() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceEndpoints", reflect.TypeOf((*MockEventStore)(nil).ServiceEndpoints))
}
