// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qpoint-io/qtap/pkg/services (interfaces: RegistryAccessor)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/registry_accessor.go -package mocks . RegistryAccessor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	services "github.com/qpoint-io/qtap/pkg/services"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistryAccessor is a mock of RegistryAccessor interface.
type MockRegistryAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryAccessorMockRecorder
	isgomock struct{}
}

// MockRegistryAccessorMockRecorder is the mock recorder for MockRegistryAccessor.
type MockRegistryAccessorMockRecorder struct {
	mock *MockRegistryAccessor
}

// NewMockRegistryAccessor creates a new mock instance.
func NewMockRegistryAccessor(ctrl *gomock.Controller) *MockRegistryAccessor {
	mock := &MockRegistryAccessor{ctrl: ctrl}
	mock.recorder = &MockRegistryAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistryAccessor) EXPECT() *MockRegistryAccessorMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRegistryAccessor) Get(serviceType services.ServiceType) services.ServiceFactory {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", serviceType)
	ret0, _ := ret[0].(services.ServiceFactory)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockRegistryAccessorMockRecorder) Get(serviceType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRegistryAccessor)(nil).Get), serviceType)
}
