// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qpoint-io/qtap/pkg/services (interfaces: ServiceFactory)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/service_factory.go -package mocks . ServiceFactory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	services "github.com/qpoint-io/qtap/pkg/services"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceFactory is a mock of ServiceFactory interface.
type MockServiceFactory struct {
	ctrl     *gomock.Controller
	recorder *MockServiceFactoryMockRecorder
	isgomock struct{}
}

// MockServiceFactoryMockRecorder is the mock recorder for MockServiceFactory.
type MockServiceFactoryMockRecorder struct {
	mock *MockServiceFactory
}

// NewMockServiceFactory creates a new mock instance.
func NewMockServiceFactory(ctrl *gomock.Controller) *MockServiceFactory {
	mock := &MockServiceFactory{ctrl: ctrl}
	mock.recorder = &MockServiceFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceFactory) EXPECT() *MockServiceFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockServiceFactory) Create(ctx context.Context) (services.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx)
	ret0, _ := ret[0].(services.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceFactoryMockRecorder) Create(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockServiceFactory)(nil).Create), ctx)
}

// FactoryType mocks base method.
func (m *MockServiceFactory) FactoryType() services.ServiceType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FactoryType")
	ret0, _ := ret[0].(services.ServiceType)
	return ret0
}

// FactoryType indicates an expected call of FactoryType.
func (mr *MockServiceFactoryMockRecorder) FactoryType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FactoryType", reflect.TypeOf((*MockServiceFactory)(nil).FactoryType))
}

// Init mocks base method.
func (m *MockServiceFactory) Init(ctx context.Context, config any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockServiceFactoryMockRecorder) Init(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockServiceFactory)(nil).Init), ctx, config)
}

// ServiceType mocks base method.
func (m *MockServiceFactory) ServiceType() services.ServiceType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceType")
	ret0, _ := ret[0].(services.ServiceType)
	return ret0
}

// ServiceType indicates an expected call of ServiceType.
func (mr *MockServiceFactoryMockRecorder) ServiceType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceType", reflect.TypeOf((*MockServiceFactory)(nil).ServiceType))
}
