
version: 2
services:
  event_stores:
    - type: stdout
  object_stores:
    - type: stdout
stacks:
  basic_reporting:
    plugins:
      - type: http_capture
        config:
          level: summary # (none|summary|details|full)
          format: text # (json|text)
          rules:
            - name: full log httpbin.org
              expr: request.host == "httpbin.org"
              level: full
            - name: details log on 500
              expr: response.status >= 500
              level: details
            - name: full log on 400
              expr: response.status >= 400 && response.status < 500
              level: full

      - type: report_usage
tap:
  direction: egress # (egress|egress-external|egress-internal)
  ignore_loopback: true
  audit_include_dns: false
  http:
    stack: basic_reporting
