// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qpoint-io/qtap/pkg/httpclient (interfaces: HttpClient)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/http_client_mock.go -package mocks . HttpClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHttpClient is a mock of HttpClient interface.
type MockHttpClient struct {
	ctrl     *gomock.Controller
	recorder *MockHttpClientMockRecorder
	isgomock struct{}
}

// MockHttpClientMockRecorder is the mock recorder for MockHttpClient.
type MockHttpClientMockRecorder struct {
	mock *MockHttpClient
}

// NewMockHttpClient creates a new mock instance.
func NewMockHttpClient(ctrl *gomock.Controller) *MockHttpClient {
	mock := &MockHttpClient{ctrl: ctrl}
	mock.recorder = &MockHttpClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpClient) EXPECT() *MockHttpClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockHttpClient) Get(url string) (io.ReadCloser, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", url)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockHttpClientMockRecorder) Get(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHttpClient)(nil).Get), url)
}

// GetJSON mocks base method.
func (m *MockHttpClient) GetJSON(url string, out any) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJSON", url, out)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJSON indicates an expected call of GetJSON.
func (mr *MockHttpClientMockRecorder) GetJSON(url, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJSON", reflect.TypeOf((*MockHttpClient)(nil).GetJSON), url, out)
}

// GetYAML mocks base method.
func (m *MockHttpClient) GetYAML(url string, out any) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetYAML", url, out)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetYAML indicates an expected call of GetYAML.
func (mr *MockHttpClientMockRecorder) GetYAML(url, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetYAML", reflect.TypeOf((*MockHttpClient)(nil).GetYAML), url, out)
}

// PostJSON mocks base method.
func (m *MockHttpClient) PostJSON(url string, payload, out any) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostJSON", url, payload, out)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostJSON indicates an expected call of PostJSON.
func (mr *MockHttpClientMockRecorder) PostJSON(url, payload, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostJSON", reflect.TypeOf((*MockHttpClient)(nil).PostJSON), url, payload, out)
}
