// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qpoint-io/qtap/pkg/ebpf/tls (interfaces: Probe)
//
// Generated by this command:
//
//	mockgen --destination=probe_mock.go --package tls . Probe
//

// Package tls is a generated GoMock package.
package tls

import (
	context "context"
	io "io"
	reflect "reflect"

	binutils "github.com/qpoint-io/qtap/pkg/binutils"
	gomock "go.uber.org/mock/gomock"
)

// MockProbe is a mock of Probe interface.
type MockProbe struct {
	ctrl     *gomock.Controller
	recorder *MockProbeMockRecorder
	isgomock struct{}
}

// MockProbeMockRecorder is the mock recorder for MockProbe.
type MockProbeMockRecorder struct {
	mock *MockProbe
}

// NewMockProbe creates a new mock instance.
func NewMockProbe(ctrl *gomock.Controller) *MockProbe {
	mock := &MockProbe{ctrl: ctrl}
	mock.recorder = &MockProbeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProbe) EXPECT() *MockProbeMockRecorder {
	return m.recorder
}

// Attach mocks base method.
func (m *MockProbe) Attach(ctx context.Context, target *ExeLinkAttachable, result ProbeScanResult) (io.Closer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attach", ctx, target, result)
	ret0, _ := ret[0].(io.Closer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Attach indicates an expected call of Attach.
func (mr *MockProbeMockRecorder) Attach(ctx, target, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attach", reflect.TypeOf((*MockProbe)(nil).Attach), ctx, target, result)
}

// AttachLibrary mocks base method.
func (m *MockProbe) AttachLibrary(ctx context.Context, target *ExeLibraryAttachable, result ProbeScanResult) (io.Closer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachLibrary", ctx, target, result)
	ret0, _ := ret[0].(io.Closer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AttachLibrary indicates an expected call of AttachLibrary.
func (mr *MockProbeMockRecorder) AttachLibrary(ctx, target, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachLibrary", reflect.TypeOf((*MockProbe)(nil).AttachLibrary), ctx, target, result)
}

// Close mocks base method.
func (m *MockProbe) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockProbeMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockProbe)(nil).Close))
}

// Name mocks base method.
func (m *MockProbe) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockProbeMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockProbe)(nil).Name))
}

// Scan mocks base method.
func (m *MockProbe) Scan(ctx context.Context, target *ExeElfScannable) (ProbeScanResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scan", ctx, target)
	ret0, _ := ret[0].(ProbeScanResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scan indicates an expected call of Scan.
func (mr *MockProbeMockRecorder) Scan(ctx, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockProbe)(nil).Scan), ctx, target)
}

// ScanLibrary mocks base method.
func (m *MockProbe) ScanLibrary(ctx context.Context, ef *binutils.Elf) (ProbeScanResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanLibrary", ctx, ef)
	ret0, _ := ret[0].(ProbeScanResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScanLibrary indicates an expected call of ScanLibrary.
func (mr *MockProbeMockRecorder) ScanLibrary(ctx, ef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanLibrary", reflect.TypeOf((*MockProbe)(nil).ScanLibrary), ctx, ef)
}

// SharedLibraries mocks base method.
func (m *MockProbe) SharedLibraries() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SharedLibraries")
	ret0, _ := ret[0].(string)
	return ret0
}

// SharedLibraries indicates an expected call of SharedLibraries.
func (mr *MockProbeMockRecorder) SharedLibraries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SharedLibraries", reflect.TypeOf((*MockProbe)(nil).SharedLibraries))
}
