// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qpoint-io/qtap/pkg/ebpf/tls (interfaces: TargetScanner)
//
// Generated by this command:
//
//	mockgen --destination=target_scanner_mock.go --package tls . TargetScanner
//

// Package tls is a generated GoMock package.
package tls

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTargetScanner is a mock of TargetScanner interface.
type MockTargetScanner struct {
	ctrl     *gomock.Controller
	recorder *MockTargetScannerMockRecorder
	isgomock struct{}
}

// MockTargetScannerMockRecorder is the mock recorder for MockTargetScanner.
type MockTargetScannerMockRecorder struct {
	mock *MockTargetScanner
}

// NewMockTargetScanner creates a new mock instance.
func NewMockTargetScanner(ctrl *gomock.Controller) *MockTargetScanner {
	mock := &MockTargetScanner{ctrl: ctrl}
	mock.recorder = &MockTargetScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTargetScanner) EXPECT() *MockTargetScannerMockRecorder {
	return m.recorder
}

// Attach mocks base method.
func (m *MockTargetScanner) Attach(ctx context.Context, pid int, path string, res *ScanResult) (io.Closer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attach", ctx, pid, path, res)
	ret0, _ := ret[0].(io.Closer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Attach indicates an expected call of Attach.
func (mr *MockTargetScannerMockRecorder) Attach(ctx, pid, path, res any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attach", reflect.TypeOf((*MockTargetScanner)(nil).Attach), ctx, pid, path, res)
}

// AttachContainer mocks base method.
func (m *MockTargetScanner) AttachContainer(ctx context.Context, res *ContainerScanResult) (io.Closer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachContainer", ctx, res)
	ret0, _ := ret[0].(io.Closer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AttachContainer indicates an expected call of AttachContainer.
func (mr *MockTargetScannerMockRecorder) AttachContainer(ctx, res any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachContainer", reflect.TypeOf((*MockTargetScanner)(nil).AttachContainer), ctx, res)
}

// Close mocks base method.
func (m *MockTargetScanner) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockTargetScannerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTargetScanner)(nil).Close))
}

// Scan mocks base method.
func (m *MockTargetScanner) Scan(ctx context.Context, path string) (*ScanResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scan", ctx, path)
	ret0, _ := ret[0].(*ScanResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scan indicates an expected call of Scan.
func (mr *MockTargetScannerMockRecorder) Scan(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockTargetScanner)(nil).Scan), ctx, path)
}

// ScanContainer mocks base method.
func (m *MockTargetScanner) ScanContainer(ctx context.Context, id, root string) (*ContainerScanResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanContainer", ctx, id, root)
	ret0, _ := ret[0].(*ContainerScanResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScanContainer indicates an expected call of ScanContainer.
func (mr *MockTargetScannerMockRecorder) ScanContainer(ctx, id, root any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanContainer", reflect.TypeOf((*MockTargetScanner)(nil).ScanContainer), ctx, id, root)
}
